
#
# This file contains the default values used by the helm chart installation.
#

###############################################################################
# Global configuration which is available to all sub-charts

global:
  # Common image variables
  image:
    repository: icr.io/isva/verify-access:10.0.8.0
    pullPolicy: IfNotPresent

  # Image credentials.
  imageCredentials:
    dockerSecret: ""

  # Container configuration.
  container:
    snapshot:           ""
    fixpacks:           ""
    timezone:            "Asia/Ho_Chi_Minh"
    CONFIG_SERVICE_TLS_CACERT:           "disabled"

  # Persistence Storage
  persistence:
    enabled: true

  # Data Volume
  dataVolume:
    existingClaimName: ""
    size: 1Gi

###############################################################################
# Resource Configuration.

# Information on computing resources can be found at:
#    http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 1Gi
    cpu:    1000m
  limits:
    memory: 2Gi
    cpu:    2000m

###############################################################################
# Service Configuration.

service:
  servicename:
  type: NodePort
  nodePort:
